import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeroSection from '@/components/HeroSection'



export default function Home() {
  return (
    <>
      <Head>
        <title>My DevFolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='relative px-[20px]  md:px-[80px]'>
        <HeroSection />
      </main>
    </>
  )
}
